---
- name: Téléchargement des archives
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip"
    dest: /tmp/terraform_{{ version }}_linux_amd64.zip
    checksum: "{{ checksum }}"

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Installation unzip
  become: yes
  become_user: root
  package:
    name: unzip
    state: present

- name: Décompression des archives
  unarchive:
    remote_src: yes
    src: /tmp/terraform_{{ version }}_linux_amd64.zip
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
