
- name: Lecture des variables
  include_vars:
    file: vars.yml

- name: Téléchargement du script d'installation
  get_url:
    url: https://get.helm.sh/helm-v{{ version }}-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    checksum: "{{ checksum }}"

- name: Création du répertoire de décompression
  file:
    path: "/tmp/helm"
    state: directory

- name: Décompression des archives
  unarchive:
    src: /tmp/helm.tar.gz
    dest: "/tmp/helm"

- name: Déplacement des fichiers depuis linux-amd64
  copy: 
    remote_src: True
    src: /tmp/helm/linux-amd64/
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
