
- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Téléchargement du script d'installation
  get_url:
    url: https://kind.sigs.k8s.io/dl/v{{ version }}/kind-linux-amd64
    dest: "{{ install_dir }}/kind"
    checksum: "{{ checksum }}"
    mode: '0755'

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes

- name: Copie du fichier de configuration Kind
  become: yes
  become_user: root
  copy:
    src: files/kind.yml
    dest: /opt/kind.yml
