
- name: Lecture des variables
  include_vars:
    file: vars.yml

- name: Téléchargement du script d'installation
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.4/kustomize_v4.5.4_linux_amd64.tar.gz
    dest: /tmp/kustomize.tar.gz

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    src: /tmp/kustomize.tar.gz
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
