
- name: Téléchargement des archives
  get_url:
    url: "https://download-cdn.jetbrains.com/idea/ideaIC-{{ version }}.tar.gz"
    dest: /tmp/idea-{{ version }}.tar.gz
    checksum: "{{ checksum }}"

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    remote_src: yes
    src: /tmp/idea-{{ version }}.tar.gz
    dest: "{{ install_dir }}"

- name: Récupération du nom du dossier décompressé
  find:
    paths: "{{ install_dir }}"
    file_type: directory
    patterns: 'idea-IC-{{ build }}'
  register: idea_home

- name: Ajout du script d'ajout au path
  template:
    src: currentidea.sh.j2
    dest: ~/.bashrc.d/currentidea.sh

- name: Ajout du racourci Desktop
  template:
    src: idea.desktop.j2
    dest: ~/.local/share/applications/idea.desktop
    mode: '0600'
