
- name: Téléchargement du script d'installation
  get_url:
    url: https://github.com/ahmetb/kubectx/releases/download/v{{ version }}/kubens_v{{ version }}_linux_x86_64.tar.gz
    dest: /tmp/kubens.tar.gz
    checksum: "{{ checksum }}"

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    src: /tmp/kubens.tar.gz
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
