
- name: Lecture des variables
  include_vars:
    file: vars.yml

- name: Téléchargement des archives
  get_url:
    url: "https://dl.pstmn.io/download/latest/linux64"
    dest: /tmp/postman.tar.gz

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    remote_src: yes
    src: /tmp/postman.tar.gz
    dest: "{{ install_dir }}"
