
- name: Téléchargement des archives
  get_url:
    url: "{{ item.url }}"
    dest: /tmp/openjdk-{{ item.version }}.tar.gz
    checksum: "{{ item.checksum }}"
  loop: "{{ versions }}"

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    remote_src: yes
    src: /tmp/openjdk-{{ item.version }}.tar.gz
    dest: "{{ install_dir }}"
  loop: "{{ versions }}"

- name: Récupération du nom du dossier décompressé
  find:
    paths: "{{ install_dir }}"
    file_type: directory
    patterns: 'jdk-{{ item.version }}*'
  loop: "{{ versions }}"
  register: java_home

- name: Ajout de l'éxécutable au path
  blockinfile:
    dest: ~/.profile
    block: |
      export JAVA_HOME={{ java_home.results[0].files[0].path }}
      export PATH=$JAVA_HOME/bin:$PATH
    marker: "# {mark} JAVA BLOCK"
    create: yes
