
- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Téléchargement du script d'installation
  get_url:
    url: https://github.com/jqlang/jq/releases/download/jq-{{ version }}/jq-linux-amd64
    dest: "{{ install_dir }}/jq"
    mode: '0755'

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
