
- name: Lecture des variables
  include_vars:
    file: vars.yml

- name: Téléchargement du script d'installation
  get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-{{ version }}-linux-x86_64.tar.gz
    checksum: "{{ checksum }}"
    dest: /tmp/gcloud.tar.gz

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    src: /tmp/gcloud.tar.gz
    dest: "{{ install_dir }}"

- name: Exécution du script d'installation
  shell: "{{ install_dir }}/google-cloud-sdk/install.sh --quiet"

- name: Ajout de l'autocompletion
  lineinfile:
    path: ~/.profile
    line: source {{ install_dir }}/google-cloud-sdk/completion.bash.inc
    create: yes

- name: Ajout des commandes dans le path
  lineinfile:
    path: ~/.profile
    line: source {{ install_dir }}/google-cloud-sdk/path.bash.inc
    create: yes
