---
- name: Ensure required packages are installed
  become: yes
  apt:
    name: 
      - curl
      - tar
    state: present

- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'

- name: Download Google Cloud CLI with checksum verification
  get_url:
    url: "{{ gcloud_cli_url }}"
    dest: "/tmp/google-cloud-cli-linux-x86_64.tar.gz"
    checksum: "{{ checksum }}"

- name: Extract Google Cloud CLI
  unarchive:
    src: "/tmp/google-cloud-cli-linux-x86_64.tar.gz"
    dest: "{{ install_dir }}"
    remote_src: yes

- name: Run the installation script
  command: "./install.sh --quiet"
  args:
    chdir: "{{ install_dir }}/google-cloud-sdk"

- name: Add variables in shell configuration
  blockinfile:
    dest: ~/.profile
    block: |
      export PATH="$PATH:{{ install_dir }}/google-cloud-sdk/bin"
    marker: "# {mark} GCLOUD BLOCK"
    create: yes
