
- name: Téléchargement du script d'installation
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    dest: /tmp/installnvm.sh
    mode: '0755'

- name: Exécution du script d'installation
  shell: /tmp/installnvm.sh

- name: Ajout de NVM au path via le profile
  lineinfile:
    path: ~/.profile
    line: source ~/.nvm/nvm.sh
    create: yes

- name: Installation de Node LTS
  shell: source ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
