
- name: Téléchargement du script d'installation
  get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v{{ version }}/cmctl-linux-amd64.tar.gz
    dest: /tmp/cmctl.tar.gz

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    src: /tmp/cmctl.tar.gz
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
