all:
  vars:
    flux: true
    gcloud: true
    helm: true
    jq: true
    k9s: true
    kind: true
    kubectx: true
    kubens: true
    kustomize: true
    maven: true
    ngrok: true
    node: true
    openjdk: true
    terraform: true
  hosts:
    localhost:
      ansible_connection: local