- hosts: all
  roles:
    - role: flux
      when: flux
    - role: gcloud
      when: gcloud
    - role: helm
      when: helm
    - role: jq
      when: jq
    - role: k9s
      when: k9s
    - role: kind
      when: kind
    - role: kubectx
      when: kubectx
    - role: kubens
      when: kubens
    - role: kustomize
      when: kustomize
    - role: maven
      when: maven
    - role: ngrok
      when: ngrok
    - role: node
      when: node
    - role: openjdk
      when: openjdk
    - role: shell
      when: shell
    - role: terraform
      when: terraform
