
- hosts: all
  tasks:
    - name: Création du répertoire ~/.bashrc.d
      file:
        path: "~/.bashrc.d"
        state: directory
    - name: Sourcing des fichiers dans ~/.bashrc.d
      blockinfile:
        dest: "~/.bashrc"
        block: |
          while read filename
          do
            source "$filename"
          done < <(find -L ~/.bashrc.d -type f)
          
        marker: '# {mark} ANSIBLE MANAGED BLOCK - ~.bashrc.d'
        insertbefore: BOF
        create: yes

- hosts: all
  roles:
    - role: gcloud
      when: gcloud
    - role: k9s
      when: k9s
    - role: node
      when: node
    - role: openjdk
      when: openjdk
    - role: maven
      when: maven
    - role: slack
      when: slack
