- hosts: all
  roles:
    - role: gcloud
      when: gcloud
    - role: k9s
      when: k9s
    - role: node
      when: node
    - role: openjdk
      when: openjdk
    - role: slack
      when: slack
