
- hosts: all
  tasks:
    - name: Création du répertoire ~/.bashrc.d
      file:
        path: "~/.bashrc.d"
        state: directory
    - name: Sourcing des fichiers dans ~/.bashrc.d
      blockinfile:
        dest: "~/.bashrc"
        block: |
          while read filename
          do
            source "$filename"
          done < <(find -L ~/.bashrc.d -type f)
          
        marker: '# {mark} ANSIBLE MANAGED BLOCK - ~.bashrc.d'
        insertbefore: BOF
        create: yes

- hosts: all
  roles:
    - role: docker
      when: docker
      become: true
    - role: gcloud
      when: gcloud
    - role: k9s
      when: k9s
    - role: kubectx
      when: kubectx
    - role: kubens
      when: kubens
    - role: kustomize
      when: kustomize
    - role: kind
      when: kind
    - role: node
      when: node
    - role: openjdk
      when: openjdk
    - role: maven
      when: maven
    - role: idea
      when: idea
    - role: slack
      when: slack
    - role: postgresql
      when: postgresql
      become: true
      vars:
        postgresql_version: 12
    - role: dbeaver
      when: dbeaver
    - role: postman
      when: postman
    - role: terraform
      when: terraform
    - role: flux
      when: flux
