
- name: Lecture des variables
  include_vars:
    file: vars.yml

- name: Téléchargement des archives
  get_url:
    url: "https://github.com/fluxcd/flux2/releases/download/v{{ version }}/flux_{{ version }}_linux_amd64.tar.gz"
    dest: /tmp/flux_{{ version }}_linux_amd64.tar.gz
    checksum: "{{ checksum }}"

- name: Création du répertoire d'installation
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Décompression des archives
  unarchive:
    remote_src: yes
    src: /tmp/flux_{{ version }}_linux_amd64.tar.gz
    dest: "{{ install_dir }}"

- name: Ajout de l'éxécutable au path
  lineinfile:
    path: ~/.profile
    line: export PATH="{{ install_dir }}:$PATH"
    create: yes
